apiVersion: v1
kind: Service
metadata:
  name: api-customer-service
spec:
  selector:
    app: api-customer-service
  ports:
    - port: 3333
      protocol: TCP
      targetPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: client-app
spec:
  selector:
    app: myapp
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
